/* DVD ACTION TYPE BEGIN*/
export const DVD_MAKE_REQ = "DVD_MAKE_REQ";
export const DVD_REQ_GETALL_SUCC = "DVD_REQ_GETALL_SUCC";
export const DVD_REQ_GETALL_FAIL = "DVD_REQ_GETALL_FAIL";
export const DVD_OPEN_POPUP = "DVD_OPEN_POPUP";
export const DVD_REQ_ADD_SUCC = "DVD_REQ_ADD_SUCC";
export const DVD_REQ_UPDATE_SUCC = "DVD_REQ_UPDATE_SUCC";
export const DVD_REQ_DELETE_SUCC = "DVD_REQ_DELETE_SUCC";
export const DVD_REQ_GETBYCODE_SUCC = "DVD_REQ_GETBYCODE_SUCC";
/* DVD ACTION TYPE END */

/* FRIEND ACTION TYPE BEGIN*/
export const FRIEND_MAKE_REQ = "FRIEND_MAKE_REQ";
export const FRIEND_REQ_GETALL_SUCC = "FRIEND_REQ_GETALL_SUCC";
export const FRIEND_REQ_GETALL_FAIL = "FRIEND_REQ_GETALL_FAIL";
export const FRIEND_OPEN_POPUP = "FRIEND_OPEN_POPUP";
export const FRIEND_REQ_ADD_SUCC = "FRIEND_REQ_ADD_SUCC";
export const FRIEND_REQ_UPDATE_SUCC = "FRIEND_REQ_UPDATE_SUCC";
export const FRIEND_REQ_DELETE_SUCC = "FRIEND_REQ_DELETE_SUCC";
export const FRIEND_REQ_GETBYCODE_SUCC = "FRIEND_REQ_GETBYCODE_SUCC";
/* FRIEND ACTION TYPE END */

/* LOAN ACTION TYPE BEGIN*/
export const LOAN_MAKE_REQ = "LOAN_MAKE_REQ";
export const LOAN_REQ_GETALL_SUCC = "LOAN_REQ_GETALL_SUCC";
export const LOAN_REQ_GETALL_FAIL = "LOAN_REQ_GETALL_FAIL";
export const LOAN_OPEN_POPUP = "LOAN_OPEN_POPUP";
export const LOAN_REQ_ADD_SUCC = "LOAN_REQ_ADD_SUCC";
export const LOAN_REQ_UPDATE_SUCC = "LOAN_REQ_UPDATE_SUCC";
export const LOAN_REQ_DELETE_SUCC = "LOAN_REQ_DELETE_SUCC";
export const LOAN_REQ_GETBYCODE_SUCC = "LOAN_REQ_GETBYCODE_SUCC";
/* LOAN ACTION TYPE END */
